apps/account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    # login logout and register
    path('login-register/', views.login_register, name='login_register'),
    path('logout/', views.logout, name='logout'),
    path('register/complete-profile/', views.GetUserProfileInfo.as_view(), name='register_profile'),

    # reset password
    path('reset-password', views.reset_password, name='reset_password'),
    path('reset-password/send-code', views.reset_password_send, name='reset_password_send_code'),
    path('reset-password/check-code', views.reset_password_check, name='reset_password_check_code'),
    path('reset-password/set', views.reset_password_set, name='reset_password_set'),

    # club admin
    path('club-admin/home-admin', views.HomeAdmin.as_view(), name='home-admin'),
    path('club-admin/users', views.Users.as_view(), name='users'),

    path('user-profile/<int:user_id>', views.UserProfileView.as_view(), name='user-profile'),
    path('user-profile/update/', views.UserProfileUpdate.as_view(), name='user_profile_update'),
    path('user-profile/<int:user_id>/delete', views.UserProfileDelete.as_view(), name='user-profile-delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.account.views import login_register


urlpatterns = [
    path('admin/login/', login_register, name='login_register'),
    path('admin/', admin.site.urls),
    path('u/', include('apps.account.urls', namespace='account')),
    path('', include('apps.public.urls', namespace='public')),
    path('diet/', include('apps.diet.urls', namespace='diet')),
    path('exercise/', include('apps.exercise.urls', namespace='exercise')),
    path('package/', include('apps.package.urls', namespace='package')),
    path('order/', include('apps.order.urls', namespace='order')),
]

# Serve static files on dev
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/program/templates/program/diet-plan.html
{% extends 'base/base_template.html' %}
{% load static %}

{% block Title %}
    برنامه غذایی
{% endblock %}

{% block Link %}
    <link rel="stylesheet" href="{% static 'front/vendors/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'front/styles/user-profile.css' %}">
    <link rel="stylesheet" href="{% static 'front/styles/diet-plan.css' %}">
    <link rel="stylesheet" href="{% static 'front/styles/all.css' %}">
{% endblock %}

{% block Content %}
    <body>
    <section class="main-page">
        <main class="col-md-12 col-lg-12 content-main-admin">
            {% include 'base/components/header.html' %}
            <h2 class="text-white m-4">برنامه غذایی</h2>
            {% if user.is_admin_user %}
                <section class="user-profile col-12 col-lg-11">
                    <div class="col-2 col-md-1">
                        <div class="user-img">
                            <img src="{{ user_detail.get_image_url }}" alt="{{ user_detail.get_full_name }}">
                        </div>
                    </div>
                    <div class="col-10 col-md-11">
                        <div class="specifications">
                            <div class="col-4">
                                <div class="specifications-item">
                                    {{ user_detail.get_full_name }}
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="specifications-item">
                                    {{ user_detail.info.national_code|default:'ثبت نشده است' }}
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="specifications-item">
                                    {{ user_detail.get_raw_phonenumber }}
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="specifications-item">
                                    {% if user_detail.info.weight %}
                                        {{ user_detail.info.weight }}
                                        کیلوگرم
                                    {% else %}
                                        ثبت نشده است
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="specifications-item">
                                    {{ user_detail.info.height|default:'ثبت نشده است' }}
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="specifications-item">
                                    {{ user_detail.last_login }}
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            {% endif %}

            <div class="btns-table  col-12 col-lg-11">
                <div class="btn-item active">شنبه</div>
                <div class="btn-item">یکشنبه</div>
                <div class="btn-item">دوشنبه</div>
                <div class="btn-item">سه شنبه</div>
                <div class="btn-item">چهارشنبه</div>
                <div class="btn-item">پنج شنیه</div>
                <div class="btn-item">جمعه</div>
            </div>
            <section class="table-two col-12 col-lg-11">
                <div class="tables-content active">
                    <table class="table">
                        {% for program in programs0 %}
                            <tr class="{% if program.is_new %}tr-active{% endif %}">
                                <td>{{ program.food.name }}</td>
                                <td>
                                    {{ program.amount }}
                                    گرم
                                </td>
                                <td>
                                    {{ program.energy }}
                                    کالری
                                </td>
                                <td>{{ program.description }}</td>
                                <td class="datetime-convert">{{ program.get_created_at }}</td>
                            </tr>
                        {% empty %}
                            <div class="container-not-found-base">
                                <p>چیزی یافت نشد</p>
                            </div>
                        {% endfor %}
                    </table>
                </div>
                <div class="tables-content">
                    <table class="table">
                        {% for program in programs1 %}
                            <tr class="{% if program.is_new %}tr-active{% endif %}">
                                <td>{{ program.food.name }}</td>
                                <td>
                                    {{ program.amount }}
                                    گرم
                                </td>
                                <td>
                                    {{ program.energy }}
                                    کالری
                                </td>
                                <td>{{ program.description }}</td>
                                <td class="datetime-convert">{{ program.get_created_at }}</td>
                            </tr>
                        {% empty %}
                            <div class="container-not-found-base">
                                <p>چیزی یافت نشد</p>
                            </div>
                        {% endfor %}
                    </table>
                </div>
                <div class="tables-content">
                    <table class="table">
                        {% for program in programs2 %}
                            <tr class="{% if program.is_new %}tr-active{% endif %}">
                                <td>{{ program.food.name }}</td>
                                <td>
                                    {{ program.amount }}
                                    گرم
                                </td>
                                <td>
                                    {{ program.energy }}
                                    کالری
                                </td>
                                <td>{{ program.description }}</td>
                                <td class="datetime-convert">{{ program.get_created_at }}</td>
                            </tr>
                        {% empty %}
                            <div class="container-not-found-base">
                                <p>چیزی یافت نشد</p>
                            </div>
                        {% endfor %}
                    </table>
                </div>
                <div class="tables-content">
                    <table class="table">
                        {% for program in programs3 %}
                            <tr class="{% if program.is_new %}tr-active{% endif %}">
                                <td>{{ program.food.name }}</td>
                                <td>
                                    {{ program.amount }}
                                    گرم
                                </td>
                                <td>
                                    {{ program.energy }}
                                    کالری
                                </td>
                                <td>{{ program.description }}</td>
                                <td class="datetime-convert">{{ program.get_created_at }}</td>
                            </tr>
                        {% empty %}
                            <div class="container-not-found-base">
                                <p>چیزی یافت نشد</p>
                            </div>
                        {% endfor %}
                    </table>
                </div>
                <div class="tables-content">
                    <table class="table">
                        {% for program in programs4 %}
                            <tr class="{% if program.is_new %}tr-active{% endif %}">
                                <td>{{ program.food.name }}</td>
                                <td>
                                    {{ program.amount }}
                                    گرم
                                </td>
                                <td>
                                    {{ program.energy }}
                                    کالری
                                </td>
                                <td>{{ program.description }}</td>
                                <td class="datetime-convert">{{ program.get_created_at }}</td>
                            </tr>
                        {% empty %}
                            <div class="container-not-found-base">
                                <p>چیزی یافت نشد</p>
                            </div>
                        {% endfor %}
                    </table>
                </div>
                <div class="tables-content">
                    <table class="table">
                        {% for program in programs5 %}
                            <tr class="{% if program.is_new %}tr-active{% endif %}">
                                <td>{{ program.food.name }}</td>
                                <td>
                                    {{ program.amount }}
                                    گرم
                                </td>
                                <td>
                                    {{ program.energy }}
                                    کالری
                                </td>
                                <td>{{ program.description }}</td>
                                <td class="datetime-convert">{{ program.get_created_at }}</td>
                            </tr>
                        {% empty %}
                            <div class="container-not-found-base">
                                <p>چیزی یافت نشد</p>
                            </div>
                        {% endfor %}
                    </table>
                </div>
                <div class="tables-content">
                    <table class="table">
                        {% for program in programs6 %}
                            <tr class="{% if program.is_new %}tr-active{% endif %}">
                                <td>{{ program.food.name }}</td>
                                <td>
                                    {{ program.amount }}
                                    گرم
                                </td>
                                <td>
                                    {{ program.energy }}
                                    کالری
                                </td>
                                <td>{{ program.description }}</td>
                                <td class="datetime-convert">{{ program.get_created_at }}</td>
                            </tr>
                        {% empty %}
                            <div class="container-not-found-base">
                                <p>چیزی یافت نشد</p>
                            </div>
                        {% endfor %}
                    </table>
                </div>

            </section>
        </main>
    </section>
    <script src="{% static 'front/vendors/bootstrap.min.js' %}"></script>
    <script src="{% static 'front/js/diet-plan.js' %}"></script>
    </body>
{% endblock %}
<!-- <!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>برنامه غذایی</title>

</head> -->
<!-- </html> -->

src/program/templates/program/diet_program.html
{% extends 'base/base_template.html' %}
{% load static %}

{% block Title %}
    برنامه غذایی
{% endblock %}

{% block Link %}
    <link rel="stylesheet" href="{% static 'front/vendors/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'front/styles/user-profile.css' %}">
    <link rel="stylesheet" href="{% static 'front/styles/diet-plan.css' %}">
    <link rel="stylesheet" href="{% static 'front/styles/all.css' %}">
    <link rel="stylesheet" href="{% static 'styles/programs.css' %}">
{% endblock %}

{% block Content %}
    <body>
    <section class="main-page">
        <main class="col-md-12 col-lg-12 content-main-admin">
            {% include 'base/components/header.html' %}

            <div style="display: flex; justify-content: space-between;">
                <h2 class="text-white m-4">
                    برنامه غذایی
                    <span style="font-size: 0.6em">({{ diet_program.title }})</span>
                </h2>
                <a href="{% url 'account:user-profile' diet_program.user.id %}" class="m-4">
                    <i class="fa fa-arrow-left" style="font-size: 24pt; color: white"></i>
                </a>
            </div>

            <div class="main-p-box">
                {% for daily_program in diet_program.daily_programs.all %}
                    <div class="daily-p-box">
                        <div class="daily-p-header-box">
                            <h3 style="margin-top: 0.4rem; margin-right: 0.5rem;">{{ daily_program.get_day_label }}</h3>
                        </div>

                        <div class="daily-p-main-meal-box">
                            {% for daily_meal in daily_program.daily_diet_meals.all %}
                                <div class="daily-p-meal-box">
                                    <div style="display: flex; flex-direction: column; align-items: center; border: 1px #1ab268 solid; background-color: #1ab268; padding: 0.5rem;">
                                        <h5 style="color: white;">{{ daily_meal.meal.title }}</h5>
                                        <span style="color: white; font-size: medium;">{{ daily_meal.meal.get_time }}</span>
                                    </div>
                                    <div class="daily-p-meal-food-main-box">
                                        {% for meal_food in daily_meal.meal_foods.all %}
                                            <span class="daily-p-meal-food-box">
                                                <i class="fa fa-square" style="font-size: 0.6em; margin-left: 0.5rem;"></i>
                                                <span>{{ meal_food.amount }}</span>
                                                <span style="margin: 0 0.25rem;">{{ meal_food.amount_unit }}</span>
                                                <span>{{ meal_food.food.title }}</span>
                                            </span>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% empty %}

                {% endfor %}

                <div class="daily-p-box" style="margin-top: 2rem;">
                    <div class="daily-p-header-box">
                        <h3 style="margin-top: 0.4rem; margin-right: 0.5rem;">توصیه های کلی</h3>
                    </div>
                    <div style="background-color: white; padding: 0.5rem; border-radius: 0 0 0.5rem 0.5rem;">
                        {% for recommend in diet_program.get_program_recommends %}
                            <div style="font-size: 12pt; margin-top: 0.5rem;">
                                <i class="fa fa-square" style="font-size: 0.6em; margin-left: 0.5rem;"></i>
                                <span>{{ recommend.text }}</span>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </main>
    </section>
    <script src="{% static 'front/vendors/bootstrap.min.js' %}"></script>
    <script src="{% static 'front/js/diet-plan.js' %}"></script>
    </body>
{% endblock %}