apps/order/urls.py
from django.urls import path
from . import views


app_name = 'order'

urlpatterns = [
    path('request/', views.PackageRequestView.as_view(), name='package_request'),
]

apps/package/urls.py
from django.urls import path
from . import views


app_name = 'package'

urlpatterns = [
    path('list/', views.ProductListView.as_view(), name='list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.account.views import login_register


urlpatterns = [
    path('admin/login/', login_register, name='login_register'),
    path('admin/', admin.site.urls),
    path('u/', include('apps.account.urls', namespace='account')),
    path('', include('apps.public.urls', namespace='public')),
    path('diet/', include('apps.diet.urls', namespace='diet')),
    path('exercise/', include('apps.exercise.urls', namespace='exercise')),
    path('package/', include('apps.package.urls', namespace='package')),
    path('order/', include('apps.order.urls', namespace='order')),
]

# Serve static files on dev
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/package/models.py
from django.utils.translation import gettext as _
from .enums import PackageChoices
from django.db import models


# Packages model
class Package(models.Model):
    PACKAGES = PackageChoices

    type = models.CharField(_('Package type'), max_length=128, choices=PACKAGES.choices, default=PACKAGES.DIET)
    price = models.IntegerField(_('Price'), default=0, help_text=_('Rials'))
    buy_link = models.URLField(_('Purchase link'), null=True, blank=True)
    icon = models.ImageField(_('Package icon'), upload_to='images/packages/icons', null=True, blank=True)
    fw_class = models.CharField(_('FontAwesome css class'), max_length=64, null=True, blank=True)

    created_at = models.DateTimeField(_('Create time'), auto_now_add=True)
    modified_at = models.DateTimeField(_('Modify time'), auto_now=True)

    class Meta:
        verbose_name = _('Package')
        verbose_name_plural = _('Packages')
        ordering = ('id',)

    @property
    def get_type_label(self):
        return self.get_type_display()

    def get_package_info(self):
        return self.package_info.all()

    def __str__(self) -> str:
        return f'{self.get_type_label} - {self.price}'


# PackageInfo model
class PackageInfo(models.Model):
    package = models.ForeignKey(Package, on_delete=models.CASCADE, verbose_name=_('Package'), related_name='package_info')
    text = models.CharField(_('Text'), max_length=255)

    created_at = models.DateTimeField(_('Create time'), auto_now_add=True)
    modified_at = models.DateTimeField(_('Modify time'), auto_now=True)

    class Meta:
        verbose_name = _('Package info')
        verbose_name_plural = _('Package infos')

apps/package/views.py
from django.views.generic import ListView
from .models import Package


# ProductsList view
class ProductListView(ListView):
    template_name = 'package/packages_list.html'
    model = Package
    context_object_name = 'packages'

apps/package/templates/package/packages_list.html
{% extends 'base/base_template.html' %}
{% load static %}
{% load filters %}


{% block Title %}لیست محصولات{% endblock %}

{% block Style %}
    <link rel="stylesheet" href="{% static 'front/styles/product-list.css' %} ">
{% endblock %}

{% block Content %}
    <section class="main-page">
        <!-- START HEADER -->
        {% include 'base/components/header.html' %}
        <!-- END HEADER -->

        <main class="container-fluid">
            <section class="content-main">
                <div class="d-flex flex-column w-100">
                    <h2 class="text-white">
                        محصولات <span class="font-60">(پکیج‌ها)</span>
                    </h2>

                    <div class="d-flex flex-wrap justify-content-center gap-4 mt-3 pb-4 w-100">
                        {% for package in packages %}
                            <div class="position-relative product-box">
                                <div class="d-flex flex-column align-items-center product-inner-box">
                                    <div class="d-flex justify-content-center align-items-center gap-2 p-3 w-100">
                                        {% if package.icon %}
                                            <figure>
                                                <img src="{{ package.icon.url }}" alt="Package logo" width="60" height="48">
                                            </figure>
                                        {% elif package.fw_class %}
                                            <i class="fa {{ package.fw_class }} fa-4x color-red"></i>
                                        {% else %}
                                            <i class="fa fa-heart-circle-plus fa-4x color-red"></i>
                                        {% endif %}
                                    </div>
                                    <div class="d-flex flex-column align-items-center gap-4 mt-1 mb-3 text-white inner-info-box">
                                        <span class="fw-bold text-nowrap" style="font-size: 1.25em;">
                                            پکیج <span>{{ package.get_type_label }}</span>
                                        </span>
                                        <span class="d-flex align-items-center gap-1" style="font-size: 1.1em;">
                                            <span>{{ package.price|to_tooman|format_price }}</span>
                                            <span class="font-80">تومان</span>
                                        </span>
                                    </div>
                                    <div class="mb-3">
                                        {% if not user.is_authenticated %}
                                            <a href="{% url 'account:login_register' %}" class="btn btn-danger rounded-3 mt-3 px-4">
                                                خرید پکیج
                                            </a>
                                        {% elif user|has_package:package.type %}
                                            <span class="btn btn-secondary rounded-3 mt-3 px-5">
                                                خریداری شده
                                            </span>
                                        {% else %}
                                            <a href="{% url 'order:package_request' %}?pk={{ package.id }}" class="btn btn-danger rounded-3 mt-3 px-5">
                                                خرید پکیج
                                            </a>
                                        {% endif %}
                                    </div>
                                    <div class="mt-2">
                                        <span role="button" class="text-white open-info-btn" onclick="showInfo({{ package.id }})">توضیحات</span>
                                    </div>
                                </div>
                                <div id="package-{{ package.id }}" class="package-info-box text-white">
                                    {% for info in package.get_package_info %}
                                        <div class="d-flex align-items-center gap-2 p-1">
                                            <i class="fa fa-square fa-xs"></i>
                                            <span>{{ info.text }}</span>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
        </main>
    </section>

    <script src="{% static 'front/js/main.js' %}"></script>
{% endblock %}

{% block Script %}
    <script>
        function showInfo(id){
            let box = document.getElementById(`package-${id}`);
            box.classList.toggle('package-info-box-opened');
        }
    </script>
{% endblock %}